// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhrarA-cYnif5AMRNFuh4OtOBzUj1QEts',
    appId: '1:858945243672:web:e6f7c44e7a686e8d00d16d',
    messagingSenderId: '858945243672',
    projectId: 'karaoke-520a8',
    authDomain: 'karaoke-520a8.firebaseapp.com',
    storageBucket: 'karaoke-520a8.appspot.com',
    measurementId: 'G-8HL5JQ3VCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_WSeOIXe0ksrYYKZlZi9Ul61YMJp_cgk',
    appId: '1:858945243672:android:a5d297db174b074700d16d',
    messagingSenderId: '858945243672',
    projectId: 'karaoke-520a8',
    storageBucket: 'karaoke-520a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVeT0eKS2y7S7YAH2i1pMPYkTKuG4qxfU',
    appId: '1:858945243672:ios:86b9b414c4b0c0bf00d16d',
    messagingSenderId: '858945243672',
    projectId: 'karaoke-520a8',
    storageBucket: 'karaoke-520a8.appspot.com',
    iosBundleId: 'com.example.thuctap1',
  );
}
